# Generated by Django 4.1.1 on 2022-10-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=100)),
                ("sexo", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("data_nascimento", models.DateField()),
                ("codigo_cliente", models.IntegerField()),
            ],
        ),
    ]
