# Generated by Django 4.1.1 on 2022-10-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=300)),
                ("codigo_produto", models.IntegerField()),
                ("valor_custo", models.DecimalField(decimal_places=2, max_digits=2)),
                ("valor_venda", models.DecimalField(decimal_places=2, max_digits=2)),
                ("quantidade_estoque", models.IntegerField()),
                ("fornecedor", models.CharField(max_length=100)),
                ("farbicante", models.CharField(max_length=100)),
            ],
        ),
    ]
