# Generated by Django 4.1.1 on 2022-10-31 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Produto", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="farbicante",
            new_name="fabricante",
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="valor_custo",
            new_name="valor_de_custo",
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="valor_venda",
            new_name="valor_de_venda",
        ),
    ]
